### ISSUE TITLE
Length of words

### ISSUE THREAD

**Issue by signalwerk** [vicrazumov/React.Spritz#3]
Shouldn't we give a bit more time for longer words than for shorter?

In german we have sometimes huge words.

The algorithm should have the wpm calculated over the whole phrase and then give the words depending on the length more or less time.

Or what do you think?

**Comment by vicrazumov** [comment]
Hi @signalwerk 

This sounds reasonable. My opinion is that we can add custom wpm breakpoints for exact word lengths, so that you can fine tune the speed for certain situations. E.g.,:

```
<ReactSpritz
  customWpm=[[30, 150], [40, 120]]
/>
```

Let me know, what you think. Your PR is also welcome or I can add this on this or next weekend.

**Comment by signalwerk** [comment]
hmmm... ok. your syntax would mean 30 letters per word = 150 wpm? 
Isn't that too complicated for people to use? I like the idea to give the power to the user, but probably they just like to set wpm and not think more about it.

**Comment by vicrazumov** [comment]
Hi @signalwerk 

This one is solved by [the latest commit](https://github.com/vicrazumov/React.Spritz/commit/6abc4d76272d0308c2fb8759cf42374d68b3aec7). Update to the latest version and just use the `normalized` prop to allow more time for the longer words.

The algorithm now calculates a timeout for each word based on the overall text length as you suggested, but **it cannot be less than the set wpm tempo**. E.g., with a wpm of 250, timeout for the word _und_ would be 240 ms (60000 / 250), while for the word _Schriftsteller_ it would be 574 ms (normalised by the overall text length). 

I've also added example code - give it a try and let me know your ideas.

**Comment by signalwerk** [comment]
@vicrazumov nice! thanks a lot for your work. I thought because I was not helpful with code you could probably need a CI for the new example; https://github.com/vicrazumov/React.Spritz/pull/4
